export const MAPA_MESES: Record<string, number> = {
  "FEBRERO": 0, "MARZO": 1, "ABRIL": 2, 
  "MAYO": 0, "JUNIO": 1, "JULIO": 2, 
  "SEPTIEMBRE": 0, "OCTUBRE": 1, "NOVIEMBRE": 2,
  "AGOSTO": 0, "DICIEMBRE": 2
};

export const CURRICULO_PRIMARIA: any = {
  "1er Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["El respeto: concepto y valor", "El respeto en la familia", "El respeto en el aula", "Las emociones: alegría y tristeza", "Identificación del miedo", "Gestión de emociones básicas", "Mitos de mi comunidad", "Costumbres locales", "Relación mitos y costumbres", "Valores en la convivencia", "Práctica del respeto mutuo", "Identidad y cultura propia"],
      "SEGUNDO TRIMESTRE": ["La reciprocidad: concepto", "La reciprocidad en el hogar", "Ayuda mutua en la escuela", "El valor del compartir", "Creencias religiosas locales", "Espiritualidad comunitaria", "Respeto a la fe del otro", "Ritos y ceremonias locales", "La identidad personal: quién soy", "Soy uno en relación a otros", "Pertenencia a mi comunidad", "Fortalecimiento de la identidad"],
      "TERCER TRIMESTRE": ["La inclusión: todos iguales", "Respeto a las diferencias", "Inclusión en el juego", "Igualdad de oportunidades", "La amistad: valor social", "Amistad en la familia", "Amistad en la escuela", "Relaciones interpersonales", "Autoestima: valoración propia", "Me acepto y me quiero", "Mi comunidad: espacios seguros", "Prevención en espacios inseguros"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["Sonidos vocálicos: a, e, i", "Sonidos vocálicos: o, u", "Escucha comprensiva inicial", "Letras m, p, l (lectura)", "Escritura de palabras m-p-l", "Los artículos: la – el", "Los artículos: las – los", "Letra 'y' como enlace", "Lengua Originaria: Saludos", "Lengua Extranjera: Greetings", "Lengua Extranjera: Numbers 1-10", "Lengua Extranjera: Colors"],
      "SEGUNDO TRIMESTRE": ["Letras s, d, n (lectura)", "Escritura de palabras s-d-n", "Artículos: un – una – unos", "Texto narrativo corto", "Letras t, b, f, ñ (lectura)", "Escritura de palabras t-b-f-ñ", "Combinación silábica ce – ci", "Letras ll, v, k (lectura)", "Dígrafo ch y letras z, y", "Lengua Originaria: La familia", "Lengua Extranjera: Commands", "Lengua Extranjera: Classroom objects"],
      "TERCER TRIMESTRE": ["Letras x, w, h (lectura)", "Escritura creativa inicial", "Letras j, g (casos especiales)", "Caso de la gue – gui / ge – gi", "Combinación bl – br / fl – fr", "Combinación cl – cr / gl – gr", "Combinación pl – pr / tl – tr", "Combinación dr / güe – güi", "Lengua Originaria: El cuerpo", "Lengua Extranjera: My body", "Lengua Extranjera: Fruits", "Lengua Extranjera: Animals"],
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Integrantes de la familia", "Ocupaciones y roles familiares", "Equidad varón y mujer", "Roles compartidos en el hogar", "La comunidad: autoaceptación", "Espacio geográfico familiar", "Características del paisaje", "Paisajes naturales y culturales", "Servicios básicos: agua y luz", "Salud y educación en la zona", "¿Cómo era antes mi barrio?", "Historia local del entorno"],
      "SEGUNDO TRIMESTRE": ["Fundación de mi comunidad", "Historia de la creación local", "Personajes históricos cercanos", "Costumbres de la familia", "Tradiciones comunitarias", "Seguridad en la familia", "Seguridad en la escuela", "Seguridad en la comunidad", "Derecho a la identidad", "Derecho a la libre expresión", "Deberes en el hogar", "Deberes en la escuela"],
      "TERCER TRIMESTRE": ["Fechas cívicas locales", "Efemérides de la zona", "Actividades económicas locales", "Producción y comercio regional", "Medios de transporte terrestres", "Transporte aéreo y ferroviario", "Transporte fluvial y lacustre", "Tejidos y cerámica regional", "Vestimentas del entorno", "Expresiones simbólicas locales", "Símbolos del municipio", "Símbolos del departamento"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["DIBUJO: Psicomotricidad", "Trazo libre a mano alzada", "El arte del garabato", "Control del trazo y forma", "El punto como elemento", "La línea y sus tipos", "El punto y línea en el arte", "Composiciones lineales", "Dibujo de la figura humana", "La familia en el dibujo", "Retrato de seres queridos", "Creatividad con formas"],
      "SEGUNDO TRIMESTRE": ["DIBUJO TÉCNICO: Líneas rectas", "Líneas curvas y onduladas", "Uso de la regla recta", "Diseños creativos lineales", "Caligrafía I: trazos básicos", "Legibilidad en la escritura", "PINTURA: Percepción del tono", "Colores primarios: mezclas", "Pintura con sorbete", "Composiciones de simetría", "Asimetría en la pintura", "Pintura al dedo creativa"],
      "TERCER TRIMESTRE": ["ESCULTURA: Figuras en masa", "Modelado en plastilina", "Uso de la greda local", "Creaciones tridimensionales", "MANUALIDADES: El reciclaje", "Animales con material en desuso", "Animales domésticos creativos", "Animales salvajes reciclados", "Decoraciones con papel", "Origami básico: formas", "Moldes ilustrados y recortes", "Exposición de manualidades"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Respiración básica (canto)", "Postura y emisión sonora", "Inspiración y espiración", "Higiene vocal inicial", "Himno Nacional: historia", "Himno Nacional: fraseo", "Respeto a los símbolos", "Canto de la primera estrofa", "Interpretación de rondas", "Canciones infantiles", "Sonidos en la naturaleza", "Ruidos del contexto local"],
      "SEGUNDO TRIMESTRE": ["Canciones con ritmo", "Juegos musicales rítmicos", "Expresión en Lengua Originaria", "Ritmos en Lengua Extranjera", "Lectura no convencional", "Grafismos y símbolos", "Juegos rítmicos en rondas", "Precisión rítmica (LO, LE)", "Instrumentos reciclados", "Construcción de rítmicos", "Instrumentos del contexto", "Ensamble rítmico grupal"],
      "TERCER TRIMESTRE": ["Orquesta rítmica: inicio", "Coordinación grupal vocal", "Gestos rítmicos en rondas", "Movimiento corporal rítmico", "Canciones propias (creación)", "Composición de versos", "Expresión musical libre", "Interpretación artística", "Ensamble de orquesta y coro", "Práctica vocal y rítmica", "Presentación escolar", "Cierre de gestión musical"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométricas: peso", "Medidas antropométricas: talla", "Índice de masa corporal (IMC)", "Detección de mala postura", "Salud y nutrición inicial", "Dificultades de salud física", "Juegos motores coordinativos", "Juegos tradicionales locales", "Juegos populares recreativos", "Gimnasia: procedimientos", "Formaciones en campo", "Voces de mando iniciales"],
      "SEGUNDO TRIMESTRE": ["Atletismo: técnica arrancada", "Pasos normales y coordinados", "Pasos transitorios (atletismo)", "Carrera de rendimiento (30m)", "Carrera de velocidad (50m)", "Carreras de relevo (reglas)", "Mini básquet: juegos ind.", "Drible y manejo de balón", "Juegos pre deportivos grup.", "Nutrición para el crecimiento", "Mini Voleibol: digitación", "Golpe de antebrazo inicial"],
      "TERCER TRIMESTRE": ["Fútbol: técnica de pase", "Recepción y control de balón", "Conducción de la pelota", "Reglas básicas de juego", "Tenis de mesa: simples", "Simples y dobles mixtos", "Técnica de golpe de raqueta", "Natación: familiarización", "Respiración y flotación", "Ajedrez: tablero y piezas", "Movimientos del ajedrez", "Reglas básicas de apertura"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["Partes del cuerpo humano", "Estructura externa y función", "Apariencia física y diversidad", "Respeto al cuerpo propio/ajeno", "Hábitos de higiene personal", "Alimentación saludable", "Juego, descanso y salud", "Regulación de emociones", "Cambios corporales: peso/talla", "Dentición: cuidado dental", "La Tierra y el ciclo solar", "Fenómenos del día y la noche"],
      "SEGUNDO TRIMESTRE": ["Características de las plantas", "Hábitats de la flora local", "Utilidad de los vegetales", "Cuidado de las plantas", "Plantas medicinales locales", "Propiedades preventivas", "Propiedades curativas nat.", "Uso responsable de hierbas", "Animales domésticos locales", "Animales silvestres regionales", "Características de la fauna", "Respeto a la vida animal"],
      "TERCER TRIMESTRE": ["Paisajes naturales regionales", "Características del entorno", "Cuidado del medio ambiente", "La materia: noción de objeto", "Diferencia objeto/material", "Propiedades de los materiales", "Fuentes de agua locales", "Cuidado y protección del agua", "Fenómenos naturales locales", "Incidencia del clima en zona", "Prevención de riesgos", "Respeto a la Madre Tierra"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Noción de cantidad: mucho/poco", "Espacialidad: delante/detrás", "Espacialidad: arriba/abajo", "Espacialidad: cerca/lejos", "Temporalidad: ayer/hoy/mañana", "Números naturales del 0 al 5", "Números naturales del 6 al 9", "Lectura y escritura (LC, LO)", "Recta numérica (1-9)", "Pares e impares (1-9)", "Conteo y desconteo local", "Comparación: mayor, menor"],
      "SEGUNDO TRIMESTRE": ["Adición horizontal (1 dígito)", "Adición vertical (1 dígito)", "Sustracción horizontal (1 d.)", "Sustracción vertical (1 d.)", "Problemas de suma y resta", "Figuras: cuadrado y círculo", "Figuras: triángulo y rombo", "Líneas rectas y curvas", "Líneas abiertas y cerradas", "Simetría en figuras", "Números ordinales hasta el 6º", "Números ordinales hasta 12º"],
      "TERCER TRIMESTRE": ["Números naturales hasta el 20", "Números naturales hasta el 50", "Valor posicional: U y D", "Longitud: el metro", "Masa y peso: el kilogramo", "Capacidad: el litro", "Sistema monetario local", "La hora en el reloj", "Números naturales hasta 100", "La centena (100)", "Números romanos del I al X", "Estadística: tablas y barras"]
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Artefactos de la vida diaria", "Herramientas: utilidad y uso", "Precaución en el manejo", "Uso adecuado de artefactos", "Figuras de papel: origami", "Formas básicas geométricas", "Productos tecnológicos (PC)", "El celular y sus funciones", "Radio y televisión local", "Objetos con arcilla/masa", "Juguetes con materiales", "Uso de bloques de construcción"],
      "SEGUNDO TRIMESTRE": ["Herramientas de agricultura", "Herramientas de cocina", "Seguridad en el manejo", "Limpieza técnica básica", "Teoría básica de robótica", "Robótica en el entorno", "Robótica: móviles y giros", "La bicicleta como máquina", "Materiales para juguetes", "Herramientas pertinentes", "Diseño de modelos técnicos", "Construcción de juguetes"],
      "TERCER TRIMESTRE": ["Hardware: el teclado", "Hardware: monitor y CPU", "Hardware: mouse y cámara", "Parlantes y salida audio", "Programas: manejo de Paint", "Introducción a Scratch", "Juegos en Gcompris", "Pensamiento lógico (SEBRAN)", "Software interactivo lectura", "Seguridad tecnológica", "Cuidado de equipos digitales", "Proyecto tecnológico final"]
    }
  },
  "2do Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["Equidad de género: conceptos", "Complementariedad (H/M)", "Roles familiares equitativos", "Respeto a las diferencias", "Agradecimiento Madre Tierra", "Rituales y cosmovisiones", "Ofrendas a la naturaleza", "Conexión con el entorno", "Señales naturales locales", "Símbolos culturales: fuego", "Símbolos culturales: tierra", "Interpretación de señales"],
      "SEGUNDO TRIMESTRE": ["Diversidad cultural: Bolivia", "Igualdad en la diferencia", "Respeto a la identidad propia", "Respeto a la identidad ajena", "Convivencia intercultural", "Lugares sagrados locales", "Espacios de espiritualidad", "Protección de centros rituales", "Ritualidades de mi comunidad", "Espiritualidades de los pueblos", "Significado de ritos locales", "Prácticas de fe comunitaria"],
      "TERCER TRIMESTRE": ["Principios ético morales", "Normas de convivencia paz", "Relación pacífica (H/M)", "Valores de tolerancia", "Las emociones: manejo de ira", "Expresión asertiva del enojo", "Control emocional escolar", "Autocuidado emocional", "Armonía en organizaciones", "Instituciones de la comunidad", "Normas institucionales locales", "Liderazgo y servicio infantil"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["Nombre o sustantivo: concepto", "Género y número (sustantivo)", "Sustantivos comunes/propios", "Lengua Originaria: Los nombres", "El abecedario: fonética", "La invitación: lectura/partes", "Escritura de invitaciones", "Familia de palabras (raíz)", "Uso del artículo (det/no det)", "La oración: sujeto/predicado", "Uso de la mayúscula en textos", "Lengua Extranjera: Introductions"],
      "SEGUNDO TRIMESTRE": ["La historieta: comprensión", "Producción de cómics cortos", "Uso de la coma y punto aparte", "Lengua Originaria: Comidas", "Textos descriptivos objetos", "La sílaba y su clasificación", "Monosílabas y bisílabas", "Analogías y sinónimos", "Signos de interrogación/excl.", "Lengua Extranjera: Numbers 1-30", "Textos informativos: lectura", "Conectores de secuencia"],
      "TERCER TRIMESTRE": ["La poesía: rima y ritmo", "Expresión oral de poemas", "El cuento: partes (inicio/fin)", "Estructura del nudo (cuento)", "Antónimos y uso de ce – ci", "Adjetivo calificativo (uso)", "Palabras agudas y esdrújulas", "Lengua Originaria: El saludo", "La autobiografía: quién soy", "Mapa conceptual (esquemas)", "Lengua Extranjera: Alphabet", "Lengua Extranjera: Animals"]
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Despatriarcalización hogar", "Equidad en la escuela/zona", "Vida armoniosa en familia", "Normas de convivencia social", "Reglas del grupo comunitario", "Autobiografía personajes loc.", "Héroes y líderes de mi barrio", "Evolución histórica local", "Desarrollo de la comunidad", "Identidad y pertenencia", "Respeto a las normas locales", "Convivencia pacífica escolar"],
      "SEGUNDO TRIMESTRE": ["Medios de transporte (vías)", "Vías de comunicación local", "Seguridad vial para niños", "Prevención de accidentes", "Medios de comunicación mun.", "La radio y TV al servicio", "Importancia de informar", "Instituciones locales (rol)", "Formas de organización local", "El Gobierno Municipal", "Fechas cívicas provinciales", "Efemérides del municipio"],
      "TERCER TRIMESTRE": ["Idiomas de nuestras culturas", "Música tradicional regional", "Identidad cultural municipal", "Educación vial y peatonal", "Seguridad ciudadana local", "Intercambio comercial (feria)", "Mercados y economía local", "Consumo productos nacionales", "Trabajo comunitario: Ayni", "Sistemas: Faena y Mink'a", "La Minga y apoyo mutuo", "Símbolos patrios del Estado"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["DIBUJO: creatividad libre", "Inspiración paisaje natural", "Observación de formas vivas", "Imaginación y trazo libre", "Dibujo de animales domést.", "Dibujo de animales salvajes", "Formas bidimensionales", "DIBUJO TÉCNICO: la regla", "Trazado figuras geométricas", "Diseños geométricos regional", "Arte de los pueblos (NyPIOs)", "Simbolismo en el diseño"],
      "SEGUNDO TRIMESTRE": ["Caligrafía II: enlaces pro", "Legibilidad y ritmo (letra)", "Uniformidad en la escritura", "Práctica caligráfica diaria", "PINTURA: técnicas básicas", "Pintura con lápices color", "Mezcla de colores primarios", "Pintura al dedo: texturas", "Uso de témperas y acrílicos", "Colores secundarios (LO)", "Significado cultural color", "Composiciones pictóricas"],
      "TERCER TRIMESTRE": ["ESCULTURA: modelado masa", "Uso de plastilina avanzada", "Modelado animales (greda)", "Modelado formas del contexto", "Animales salvajes en 3D", "Figuras de flora regional", "MANUALIDADES: el origami", "Origami expresivo y creativo", "Plegado de figuras útiles", "Trenzado fibras vegetales", "Tejido material reciclable", "Manualidades con residuos"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Respiración para el canto", "Ejercicios de inspiración pro", "Control de la espiración", "Postura y emisión vocal", "Himno Nacional: 1ra parte", "Himno Nacional: 2da parte", "Entonación en Lengua LO", "Canto patriótico respetuoso", "Rondas de identidad cultural", "Canciones regionales (tema)", "Sonido: intensidad (fuerte)", "Sonido: duración (largo)"],
      "SEGUNDO TRIMESTRE": ["Canciones con instrumentos", "Uso de rítmicos en rondas", "Expresión musical (LO, LE)", "Ritmos en Lengua Originaria", "Duración: redonda y blanca", "Duración: negra y corchea", "Figuras rítmicas aplicadas", "Ritmo en acciones y gestos", "Caminata y marcha rítmica", "Palmas y percusión corporal", "Instrumentos melódicos loc.", "Ensamble musical del aula"],
      "TERCER TRIMESTRE": ["Monograma y bigrama musical", "Pentagrama: líneas y espacios", "La clave de SOL (ubicación)", "La clave de FA (inicio)", "Ritmos con material reciclado", "Interpretación rítmica libre", "Danza: expresión corporal", "Desenvolvimiento escénico", "Ensamble de coro infantil", "Acompañamiento instrumental", "Ritmos folclóricos nacionales", "Presentación artística final"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométricas (P/T)", "Índice de masa corporal (IMC)", "Detección de postura (salud)", "Dificultades de salud física", "Juegos motores coordinativos", "Juegos tradicionales locales", "Juegos populares recreativos", "Gimnasia: procesos organiz.", "Formaciones en campo dep.", "Coordinación dinámica gen.", "Salud preventiva y aseo", "Higiene deportiva personal"],
      "SEGUNDO TRIMESTRE": ["Atletismo: técnica arrancada", "Pasos normales y coordinados", "Carrera de rendimiento (30m)", "Carrera de velocidad (50m)", "Carreras de relevo (reglas)", "Mini básquet: juegos grup.", "Drible y manejo de balón", "Fundamentos del básquet", "Nutrición para deportistas", "Mini Voleibol: digitación", "Golpe de antebrazo (vóley)", "Juegos de equipo pre dep."],
      "TERCER TRIMESTRE": ["Fútbol: técnica de pase", "Recepción y control balón", "Conducción y reglas juego", "Estrategia de equipo simple", "Tenis de mesa: técnica golpe", "Simples y dobles ping-pong", "Natación: familiarización", "Respiración y flotación", "Ajedrez: tablero y piezas", "Movimientos de las piezas", "Reglas básicas de apertura", "Torneo recreativo final"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["Preservación Madre Tierra", "Prácticas culturales cuidado", "Paisajes naturales locales", "Características entorno vivo", "Preservación del agua (casa)", "Cuidado del agua (escuela)", "Gestión de riesgos: zonas", "Lugares seguros (comunidad)", "Fenómenos atmosféricos loc.", "Predicción del tiempo local", "Las estaciones del año", "Clima y vida en mi región"],
      "SEGUNDO TRIMESTRE": ["Los cinco sentidos: órganos", "Función de relación (sentido)", "Salud de los sentidos (LO)", "Cuidado de vista y audición", "Alimentación saludable (nut.)", "Dieta y sistema inmune", "Salud integral del cuerpo", "Actividad física y bienestar", "Bienestar emocional infantil", "Higiene personal diaria", "Diferencias biológicas (H/M)", "Similitudes biológicas (H/M)"],
      "TERCER TRIMESTRE": ["Características de las plantas", "Necesidades vitales flora", "Deforestación: causas", "Cambio climático y Madre T.", "Animales: equilibrio natural", "Fauna como factor ambiental", "Animales vertebrados (inicio)", "La materia: noción básica", "Propiedades físicas locales", "Estados de la materia (ent.)", "Cuidado ecosistemas reg.", "Prevención ambiental final"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Números del 101 al 500", "Números del 501 al 1000", "Lectura y escritura (1000)", "Recta numérica (101-1000)", "Comparación: mayor y menor", "Antecesor y sucesor (1000)", "Valor posicional: centenas", "Números pares/impares (1000)", "Adición de tres dígitos (V)", "Adición de tres dígitos (H)", "Propiedades de la adición", "Patrones numéricos hasta 100"],
      "SEGUNDO TRIMESTRE": ["Sustracción de tres dígitos", "Operaciones de resta (V/H)", "Propiedades de la sustracción", "Problemas de suma y resta", "Rectas paralelas/perpendic.", "Figuras y cuerpos geomét.", "Construcción de cuerpos G.", "Simetría en figuras del ent.", "Eje de simetría (práctica)", "Noción de fracciones (1/2)", "Tercio y cuarto de unidad", "Representación gráfica (Frac)"],
      "TERCER TRIMESTRE": ["Submúltiplos de longitud (cm)", "Submúltiplos de masa (mg)", "Submúltiplos capacidad (ml)", "Tiempo: minutos y segundos", "Sistema monetario nacional", "Operaciones con dinero (Bs)", "Números ordinales hasta 30º", "Multiplicación de un dígito", "División de un dígito (exacta)", "Números romanos hasta el L", "Registro de datos (tablas)", "Gráfico de barras y pictogr."],
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Diversidad artesanías NyPIOs", "Tecnologías de comunicación", "Señales, TICs y satélites", "Técnicas de transformación", "Transformación prod. local", "Herramientas: utilidad", "Uso adecuado en la vida", "Construcción robots ligas", "Energía elástica (juguete)", "Seguridad componentes Eléc.", "Uso de pilas y baterías", "Interruptores y conductores"],
      "SEGUNDO TRIMESTRE": ["Diseño juguete robot (Paint)", "Dibujo a mano alzada técnica", "Nociones armado de robots", "Materiales del contexto uso", "Estabilidad en estructuras", "Procesador textos Word (I)", "Producción textos digitales", "Opciones de edición Word", "Correos electrónicos (inicio)", "Gmail y Hotmail (seguridad)", "Comunicación digital ética", "Uso responsable de redes"],
      "TERCER TRIMESTRE": ["Navegadores: Google/Mozilla", "Búsqueda información segura", "Uso ético del internet", "Plataformas: Zoom/Meet", "Videoconferencias (función)", "Seguridad informática (virus)", "Antivirus y Firewall (uso)", "Mantenimiento PC básica", "Respeto identidad digital", "Netiqueta en redes sociales", "Prevención riesgos digitales", "Proyecto tecnológico final"]
    }
  },
  "3er Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["Igualdad de oportunidades", "Derechos y deberes género", "Equidad en la familia/esc.", "Práctica de justicia social", "Las normas y acuerdos grup.", "Construcción acuerdos aula", "Respeto reglas convivencia", "Responsabilidad en acuerdos", "Elementos: Agua y Tierra", "Fuego y Astros (simbolismo)", "Truenos y energía cósmica", "Conexión humana universo"],
      "SEGUNDO TRIMESTRE": ["Convivencia armónica div.", "Relación inter/intracultural", "Respeto culturas de Bolivia", "Diálogo intercultural esc.", "Símbolos espirituales loc.", "Símbolos naturales reg.", "Símbolos cósmicos pueblos", "Significado simbología rit.", "Ritos espirituales festivos", "Festividades de mi comun.", "Significado ritos locales", "Participación ritos comun."],
      "TERCER TRIMESTRE": ["Equidad género institucional", "Liderazgo femenino/masculino", "Prevención discriminación", "Oportunidades iguales todos", "Lugares sagrados diversidad", "Vestimentas cult./religiosas", "Identidad personal y cult.", "Valoración de la raíz propia", "Autoestima: concepto/cuido", "Me acepto y valoro raíces", "Estima por el otro (respeto)", "Convivencia basada estima"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["La comunicación verbal/gest.", "Elementos de comunicación", "El cuento: comprensión lect.", "Producción cuentos creativ.", "Orden alfabético/diccionario", "Serie de palabras/vocab.", "La anécdota: hechos reales", "Escritura anécdotas vividas", "Coherencia: art./sustantivo", "Lengua Originaria: Familia", "Lengua Extranjera: Intro I am", "Uso de la coma/punto aparte"],
      "SEGUNDO TRIMESTRE": ["La exposición: expresión oral", "Expresividad voz/lenguaje C.", "Textos instructivos: reglas", "Palabras dimin./aumentativas", "Trisílabas y tetrasílabas", "Lenguaje formal y coloquial", "La historieta: comprensión", "Producción cómics (mp y mb)", "Género/número del adjetivo", "Lengua Originaria: Números", "Lengua Extranjera: Clothes", "Textos literarios: caligrama"],
      "TERCER TRIMESTRE": ["Prosa y rima en la poesía", "Textos descriptivos (pron.)", "Uso nv y nf (ortografía)", "Conectores de causa texto", "La leyenda: mitos y verdades", "El verbo y tiempos verbales", "Uso de la ce – ci (reglas)", "Texto científico: coherencia", "Técnicas estudio: cuadro C.", "Lengua Originaria: El saludo", "Lengua Extranjera: Time", "Lengua Extranjera: Addition"],
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Democracia: elección líderes", "Ejercicio democrático escolar", "Gobierno Municipal: Alcalde", "Concejo Municipal y roles", "Creación/fundación municipio", "Personajes destacados loc.", "Historia comunidad regional", "Lugares culturales import.", "Actividades: ganad./agric.", "Industria en el municipio", "Producción regional/empleo", "Fechas cívicas departamento"],
      "SEGUNDO TRIMESTRE": ["Organizaciones sociales loc.", "Seguridad ciudadana prev.", "Prevención personas extrañas", "Trata y tráfico: riesgos", "Función social de medios", "Veracidad e imparcialidad", "Importancia diálogo grupal", "Consenso y respeto mutuo", "Toma decisiones colectivas", "Normas convivencia social", "Derechos ciudadanos zona", "Deberes comunidad municipal"],
      "TERCER TRIMESTRE": ["Ubicación geog. departamento", "Límites y extensión regional", "Geografía y paisajes prov.", "Fauna típica departamento", "Clima y estaciones región", "División política Bolivia", "Historia división territorial", "Recursos naturales: prop.", "Naciones originarias/Madre", "Aprovechamiento sustentable", "Derechos naciones indígenas", "Relación Madre Tierra local"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["Dibujo: contorno y silueta", "Dibujo de dintorno (detalles)", "Formas de animales y plantas", "Dibujo infantil bidimensional", "Vegetación y personas ent.", "Entorno familiar en dibujo", "La escuela como identidad", "Concepto luz en los objetos", "Aplicación sombra (volumen)", "Técnicas sombreado básico", "Composiciones claroscuro", "Creatividad luz y sombra"],
      "SEGUNDO TRIMESTRE": ["Líneas horiz. y verticales", "Líneas incl. (uso escuadra)", "Manejo preciso escuadras", "El círculo y sus elementos", "Diseños creativos compás", "Manejo compás técnico", "Caligrafía III: trazados pro", "Colores primarios/secund.", "Composiciones pictóricas", "Pintura témperas (cartul.)", "Técnica pintura plantillas", "Uso del cepillo en el arte"],
      "TERCER TRIMESTRE": ["ESCULTURA: figuras con papel", "Uso materiales diversos (3D)", "Modelado plastilina (flora)", "Modelado en arcilla (fauna)", "Escultura animales locales", "Figuras tridimens. reales", "MANUALIDADES: el collage", "Composiciones con texturas", "Recortado formas volumétr.", "Armado figuras geométr.", "Manualidades con reciclaje", "Creación de objetos útiles"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Educación de la voz: técnica", "Ejercicios inspiración vocal", "Espiración y control aire", "Postura correcta para canto", "Entonación Himnos/marchas", "Canciones calendario cívico", "Cantos corales tradicionales", "Música regional y cultural", "Cualidades: altura y timbre", "Cualidades: intens./durac.", "Discriminación audit. (son.)", "Ritmo y melodía en la voz"],
      "SEGUNDO TRIMESTRE": ["Canciones mensajes valores", "Coro infantil: armonía grup.", "Convivencia armónica canto", "Valores sociales en música", "Rítmica melodía corporal", "Recreaciones rítmicas fís.", "Coordinación rítmica/audit.", "Instrumentos viento (inicio)", "Técnica soplido/digitación", "Interpretación de melodías", "Clasificación instrumentos", "Instrumentos típicos reg."],
      "TERCER TRIMESTRE": ["Uso de escritura musical", "Notas musicales pentagrama", "Figuras y valores duración", "Lectura partituras simples", "Movimientos básicos danza", "Danzas tradicionales Bol.", "Características de bailes", "Historia de danza nacional", "Ensamble de coro y música", "Acompañamiento instrum.", "Presentación artíst. escolar", "Cierre de gestión musical"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométr.: peso", "Medidas antropométr.: talla", "Índice masa corporal (IMC)", "Detección de mala postura", "Salud y prevención física", "Dificultades salud y dep.", "Juegos motores coordinat.", "Juegos tradicionales locales", "Juegos populares recreat.", "Gimnasia: procesos educat.", "Procedimientos organizat.", "Formaciones grupales campo"],
      "SEGUNDO TRIMESTRE": ["Atletismo: técnica arrancada", "Pasos normales y coordin.", "Pasos transitorios carrera", "Carrera rendimiento (30-50m)", "Carrera de relevo (reglas)", "Mini básquet: juegos grup.", "Drible y manejo de balón", "Lanzamientos pre deport.", "Nutrición para desarrollo", "Mini Voleibol: técnica dig.", "Golpe de antebrazo (vóley)", "Higiene y aseo post-dep."],
      "TERCER TRIMESTRE": ["Fútbol: técnica de pase", "Recepción y control balón", "Conducción y reglas juego", "Estrategia equipo (Fútbol)", "Tenis de mesa: simples/M.", "Tenis mesa mixto/coordinat.", "Natación: técnica flotac.", "Estilos de natación (inic.)", "Ajedrez: tablero y piezas", "Reglas básicas de apertura", "Deportes mesa y concentrac.", "Torneo recreativo final"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["Pisos ecológicos regional", "Biodiversidad en provincia", "Equilibrio Madre Tierra", "Cuidado naturaleza local", "Preservación agua potable", "Adaptación cambio climát.", "Saneamiento básico (resid.)", "Aguas residuales y drenaje", "Alcantarillado y salud P.", "Acciones prevent. desastres", "Mochila de emergencias", "La Tierra: rotación/trasl."],
      "SEGUNDO TRIMESTRE": ["Ciclo de vida seres vivos", "Etapas crecimiento natural", "Forestación y reforestación", "Cuidado de árboles locales", "Animales vertebrados (clases)", "Animales invertebrados", "Características y diversidad", "Respeto a la vida animal", "Estados de la materia", "Energía térmica y solar", "Energía eólica (aire/viento)", "Propiedades y uso del sol"],
      "TERCER TRIMESTRE": ["Cuerpo humano: dig./resp.", "Funciones de circulación", "La nutrición y alimentos", "Manejo e higiene alimentos", "Medidas prevención salud", "Cuidado del cuerpo integral", "Autocuidado y protección", "Cuidado del otro (integr.)", "Conductas de riesgo y ayuda", "Salud integral y ejercicio", "Anatomía básica humana", "Evaluación final naturales"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Números del 1.001 al 5.000", "Números del 5.001 al 10.000", "Recta numérica/valor posic.", "Comparación cinco dígitos", "Pares/impares (1001-10000)", "Adición de cuatro dígitos", "Sustracción cuatro dígitos", "Problemas vida cotidiana", "Patrones numéricos tablas", "Secuencias de suma y resta", "Ángulos: elementos/medidas", "Círculo, radio y diámetro"],
      "SEGUNDO TRIMESTRE": ["Multiplicación en la recta", "Multiplicación tres dígitos", "Propiedades multiplicación", "Problemas multiplicación", "División dos y tres dígitos", "División exacta e inexacta", "Pruebas de la división (9)", "Operaciones combinadas", "Longitud: múltiplos metro", "Capacidad: litro/submúlt.", "Masa: gramo y múltiplos", "Sistema monetario/tiempo"],
      "TERCER TRIMESTRE": ["Fracciones: representación", "Términos, lectura y escrit.", "Fracciones homogéneas/mix.", "Simplificación fracciones", "Adición fracciones (H)", "Sustracción fracciones (H)", "Problemas con fracciones", "Estadística: tablas datos", "Gráfico barras: interpret.", "Gráfico líneas (registro)", "Organización información", "Análisis datos contexto"]
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Diversidad artesanías NyPIOs", "Tecnología en comunicación", "TICs: evolución y uso", "Técnicas transformación M.", "Transformación prod. local", "Herramientas regionales", "La tecnología en la vida", "TICs: conexión digital", "Construcción robots ligas", "Energía elástica mecanismos", "Componentes electr. básicos", "Seguridad pilas/baterías"],
      "SEGUNDO TRIMESTRE": ["Diseño juguetes robot", "Dibujo mano alzada técnica", "Diseño digital en Paint", "Planificación de un móvil", "Armado robot materiales", "Estructura y estabilidad", "Procesador textos Word", "Producción de documentos", "Opciones de edición Word", "Uso correos electrónicos", "Gmail/Hotmail (seguridad)", "Comunicación digital ética"],
      "TERCER TRIMESTRE": ["Navegadores: Google/Mozilla", "Firefox y búsqueda segura", "Plataformas video: Zoom", "Uso Google Meet (clases)", "Seguridad informát. (virus)", "Antivirus y Firewall (uso)", "Mantenimiento computadoras", "Figuras básicas origami", "Productos técnicos context.", "Herramientas cocina/campo", "Uso adecuado artefactos", "Proyecto tecnológico final"]
    }
  },
  "4to Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["Reciprocidad en la familia", "Complementariedad (M/V)", "Identidad personal y cultural", "Igualdad en las costumbres", "Diversidad cultural regional", "Respeto a las manifestaciones", "La conducta humana (conceptos)", "El autocontrol personal", "Gestión de las emociones", "Valores de convivencia social", "Principios de respeto mutuo", "Identidad y pertenencia"],
      "SEGUNDO TRIMESTRE": ["El Vivir Bien (introducción)", "Interrelación intra e interpersonal", "Equilibrio cuerpo y mente", "Armonía con el espíritu", "Relaciones socioculturales", "Normas de la comunidad", "Costumbres espirituales locales", "Respeto a la sabiduría ancestral", "Vivir Bien en la escuela", "Prácticas de armonía social", "Valores de equilibrio natural", "Fortalecimiento espiritual"],
      "TERCER TRIMESTRE": ["Igualdad de oportunidades", "Convivencia comunitaria real", "Vivir Bien en el entorno", "Sensibilidad social (conceptos)", "Empatía ante el sufrimiento", "Cultura de la paz y no violencia", "Resolución pacífica de conflictos", "Justicia y equidad social", "Valores de solidaridad", "Paz social en el municipio", "Derechos y deberes ciudadanos", "Compromiso con la comunidad"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["El cuento fantástico: lectura", "Sustantivos: concreto/abstracto", "Puntuación: punto aparte/seguido", "Lengua Extranjera: Verb To Be", "La noticia: estructura y partes", "Sustantivo: género y número", "Uso correcto de las mayúsculas", "Lengua Originaria: Saludos", "La leyenda: características", "Sílabas tónicas y átonas", "Dramatización: expresión gestual", "Correo electrónico: utilidad"],
      "SEGUNDO TRIMESTRE": ["La receta: lectura comprensiva", "Palabras agudas y acentuación", "El adjetivo y sus grados", "Lengua Extranjera: Possessives", "La fábula y la moraleja", "Palabras graves y tildación", "Los pronombres relativos", "Lengua Originaria: la familia", "La exposición: fase de ensayo", "La carta formal e informal", "Palabras esdrújulas (reglas)", "Modos del verbo (introducción)"],
      "TERCER TRIMESTRE": ["Reglas de juego: instrucciones", "Comas enumerativas y vocativas", "Clases de oraciones (actitud)", "Lengua Extranjera: Weather", "Portada de revista: diseño", "Verbos terminados en ger y gir", "Sujeto y predicado (núcleos)", "Lengua Originaria: animales", "Lenguaje figurado: la metáfora", "Comunicación: intencionalidad", "Técnicas: la síntesis", "Exposición con apoyo gráfico"]
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Gobierno Autónomo Departamental", "La Gobernación y sus funciones", "La Asamblea Departamental", "Organización política regional", "Turismo en el departamento", "Espacios naturales protegidos", "Derecho a una vida sin violencia", "Protección de la niñez", "Derechos de la Madre Tierra", "Leyes de cuidado ambiental", "Actividades económicas primarias", "Recursos naturales locales"],
      "SEGUNDO TRIMESTRE": ["Identidad cultural regional", "Danzas típicas del departamento", "Manifestaciones identitarias", "Organizaciones indígenas (NyPIOs)", "Organizaciones sociales locales", "Luchas sociales históricas", "La Guerra del Gas (2003)", "La Guerra del Agua (Cochabamba)", "Marchas indígenas por territorio", "Dignidad de los pueblos", "Fechas cívicas plurinacionales", "Ubicación geográfica de Bolivia"],
      "TERCER TRIMESTRE": ["Naciones de tierras bajas", "Naciones de tierras altas", "Diversidad étnica de Bolivia", "Prevención de trata y tráfico", "Uso seguro de las TICS", "Seguridad de niñas y niños", "Causas de la migración", "Consecuencias de la migración", "Despatriarcalización social", "Ejercicio del poder y equidad", "Intolerancia a la corrupción", "Ética y transparencia pública"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["Dibujo de personas y paisajes", "Paisaje urbano y rural", "Expresiones faciales básicas", "Movimiento de la figura humana", "El objeto y la luz (teoría)", "La sombra en cuerpos simples", "Degradación tonal (volumen)", "Sensación tridimensional", "Dibujo sobre temáticas sociales", "Creatividad y estilo personal", "Técnicas de trazado artístico", "Composición y equilibrio visual"],
      "SEGUNDO TRIMESTRE": ["Dibujo Técnico: NyPIOs", "Diseños creativos ancestrales", "Características artísticas locales", "Simbolismo en el arte indígena", "Creatividad con el Tangram", "Lógica y figuras geométricas", "Construcción de formas (Tangram)", "Pintura: saturación del color", "Teoría del color: intensidad", "Pintura sobre venesta y lienzo", "Temática Bodegón: frutas", "Caligrafía IV: fluidez y ritmo"],
      "TERCER TRIMESTRE": ["ESCULTURA: modelado de animales", "Modelado de la figura humana", "Vegetación con greda y arcilla", "Uso de materiales del contexto", "MANUALIDADES: diseño con relieve", "Animales con semillas y canela", "Uso de corteza y materiales", "Composiciones técnicas mixtas", "Arte decorativo regional", "Construcción de formas en 3D", "Artesanía y creatividad", "Exposición de artes finales"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Técnica vocal: relajación", "Respiración y articulación", "Emisión sonora controlada", "Higiene de la voz (cuidado)", "Himno Nacional: historia", "Himno Nacional: fraseo", "Respeto a los símbolos", "Canto de la primera estrofa", "Interpretación de rondas", "Canciones infantiles", "Sonidos en la naturaleza", "Ruidos del contexto local"],
      "SEGUNDO TRIMESTRE": ["Canciones contra la violencia", "Coro infantil: mensajes de paz", "Expresión musical (LO, LE)", "Valores en la lírica musical", "Escritura convencional: notas", "Figuras y valores musicales", "La rítmica mediante juegos", "Duración y pulso musical", "Instrumentos autóctonos: técnica", "Interpretación instrumental (LO)", "Clasificación de autóctonos", "Ensamble de instrumentos"],
      "TERCER TRIMESTRE": ["Uso del pentagrama y clave", "Lectura de notas y silencios", "Instrumento de viento (inicio)", "Técnica de soplido y digitación", "Lectura musical aplicada", "Interpretación de melodías", "Bailes y músicas tradicionales", "Ciclos agrícolas y música", "Danzas festivas regionales", "Socio-cultura de la música", "Ensamble de coro y grupos", "Presentación artística final"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométricas (P/T)", "Nutrición e hidratación diaria", "Hábitos de higiene deportiva", "Ejercicios de respiración profunda", "Capacidades condicionales (F/R)", "Capacidades coordinativas (A)", "Flexibilidad y movilidad", "Juegos de conciencia corporal", "Gimnasia: posiciones básicas", "Posiciones derivadas y giros", "Voces de mando: etapas", "Voz de mando directa (campo)"],
      "SEGUNDO TRIMESTRE": ["Mini atletismo: carreras relevo", "Resistencia física aeróbica", "Salto triple y salto largo", "Lanzamiento del vórtex", "Mini baloncesto: posiciones", "Desplazamientos en la cancha", "Pase, recepción y drible", "Reglas específicas del básquet", "Voleibol: fundamentos técnicos", "Fases del mini vóley (inicio)", "Voleo alto, bajo y saques", "Técnica de recepción inicial"],
      "TERCER TRIMESTRE": ["Fútbol de salón: técnica finta", "Regate y dominio del balón", "Técnica del portero (posición)", "Futsal: reglas y estrategia", "Handball: fundamentos básicos", "Juego recreativo por equipos", "Reglas del balonmano infantil", "Ajedrez: jugadas extraordinarias", "Tácticas de ataque y defensa", "Estrategia en juegos de mesa", "Competencia sana y valores", "Torneo recreativo de fin de año"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["Sistema locomotor: huesos/músculos", "Cuidado físico y prevención", "Sistema nervioso: estructura", "Efectos del alcohol en los nervios", "Nutrición: alimentos naturales", "Riesgos de alimentos transgénicos", "Normas de cuidado de la salud", "Prevención de enfermedades", "Protección ante la violencia", "Pedir y brindar ayuda (seguridad)", "La Tierra: la geósfera", "Fenómenos internos y externos"],
      "SEGUNDO TRIMESTRE": ["Componentes de la Madre Tierra", "Acciones de mantenimiento local", "Calentamiento global (causas)", "Resiliencia al cambio climático", "El agua segura: cualidades", "Beneficios del agua en la vida", "Saneamiento básico y salud", "Uso de contenedores (reciclaje)", "Control de inundaciones", "Fenómenos naturales y sociales", "Mapa de amenazas en Bolivia", "Prevención de riesgos regionales"],
      "TERCER TRIMESTRE": ["Clasificación de las plantas", "Clasificación de los animales", "Bosques: origen e importancia", "Características de los bosques", "Adaptación de los seres vivos", "Ecosistemas y equilibrio", "Cambios de estado: fusión", "Evaporación y solidificación", "Condensación de la materia", "Energía hidráulica y sonora", "Energía lumínica (la luz)", "Uso responsable de la energía"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Números naturales: 4 y 5 dígitos", "Antecesor y sucesor en la recta", "Valor posicional: centena de mil", "Unidad de millón (introducción)", "Adición: conmutativa y asociativa", "Elemento neutro de la adición", "Sustracción de 4 y 5 dígitos", "Operaciones combinadas (+/-)", "Resolución de problemas complejos", "Polígonos: definición y clases", "Triángulos y Cuadriláteros", "Prismas, pirámides y esferas"],
      "SEGUNDO TRIMESTRE": ["Multiplicación de 3 y 4 dígitos", "Multiplicación por descomposición", "Prueba de la exclusión del 9", "Propiedad distributiva (mult.)", "División con 3 dígitos (divisor)", "División exacta e inexacta", "El cero en el cociente (casos)", "Problemas de reparto complejo", "Números romanos hasta el mil (M)", "Escritura y uso de romanos", "Longitud: equivalencias (m)", "Masa, peso y capacidad (conv.)"],
      "TERCER TRIMESTRE": ["Fracciones: clasificación (P/I/M)", "Fracciones equivalentes", "Amplificación y reducción", "Suma y resta de fracciones (H)", "Mult. y div. de fracciones (H)", "Problemas con fracciones (H)", "Números decimales: lectura", "Comparación y orden decimal", "Decimales en la recta numérica", "Fracciones decimales (/10)", "Suma y resta de decimales", "Estadística: barras y líneas"]
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Cosecha de agua: tecnologías", "Mecanismos de riego ancestral", "Sistemas: inundación y goteo", "Riego por aspersión técnica", "Elaboración de alimentos sanos", "Procesos de deshidratación", "Seguridad alimentaria local", "Transformación de productos", "Fundamentos de la robótica", "Tipos y funciones de robots", "Características técnicas (robot)", "Robótica en la vida diaria"],
      "SEGUNDO TRIMESTRE": ["Componentes electrónicos (motores)", "Uso de transformadores pequeños", "Diseño físico del robot móvil", "Diseño digital del robot (Paint)", "Fuentes de energía: pilas/baterías", "Seguridad en circuitos básicos", "Armado de juguetes móviles", "Hoja de cálculo Excel: inicio", "Celdas y combinación básica", "Operaciones simples en tablas", "Gráfico de barras en Excel", "Organización de datos técnicos"],
      "TERCER TRIMESTRE": ["Redes sociales: uso responsable", "WhatsApp, Telegram y Facebook", "Instagram y TikTok (riesgos)", "Seguridad y ética digital", "Plataformas: Zoom y Meet", "Uso de videoconferencias", "Gestión de aula: Classroom", "Moodle y entornos virtuales", "Identidad digital y netiqueta", "Herramientas TIC para el estudio", "Prevención de delitos digitales", "Proyecto tecnológico de fin de año"]
    }
  },
  "5to Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["Justicia social: concepto", "Justicia en la comunidad", "Igualdad de derechos", "Equidad social y escolar", "Diversidad religiosa Bol.", "Respeto a las creencias", "Espiritualidad plural", "Fe en el Estado Plur.", "Dualidad en los NyPIOs", "Paridad de pensamiento", "Dualidad hombre y mujer", "Valores de paridad social"],
      "SEGUNDO TRIMESTRE": ["Bienestar común: concepto", "Vivir Bien en grupo social", "Felicidad y armonía social", "Valores de ayuda mutua", "Ceremonias espirituales", "Ritos de la diversidad Bol.", "Significado de ofrendas", "Espiritualidad y naturaleza", "Pueblos del Abyayala", "Interrelación cultural Amer.", "Diálogo entre los pueblos", "Identidad cultural regional"],
      "TERCER TRIMESTRE": ["El autoconcepto: ¿Quién soy?", "Identidad personal y valor", "Autoestima y cuidado", "Fortalecimiento del ser", "Interdependencia Madre T.", "Cuidado mutuo Tierra/Humano", "Equilibrio ambiental/social", "Responsabilidad ecológica", "Resolución de conflictos", "Cultura de la paz y diálogo", "Mediación y perdón social", "Principios de vida en paz"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["El folleto: tipos y diseño", "Diptongo e hiato (reglas)", "Analogías de sinónimos", "Lengua Extranjera: Sports", "La poesía: estructura/ritmo", "Tilde diacrítica monosílabos", "Determinantes numerales", "Lengua Originaria: Objetos", "La declamación: expresión", "Artículo informativo: partes", "Acentuación compuestas", "Técnicas: la síntesis"],
      "SEGUNDO TRIMESTRE": ["La entrevista: planificación", "Tilde interrogativa/excl.", "El verbo: modos y tiempo", "Lengua Extranjera: Buying", "La cuña radial: locución", "Uso de la B y V (ortografía)", "Sujeto y predicado (análisis)", "Lengua Originaria: Diálogo", "El reportaje: estructura", "Uso de la G y J (reglas)", "Conectores de finalidad", "Técnicas: mapa conceptual"],
      "TERCER TRIMESTRE": ["Refranes y proverbios", "Uso de la H en la escritura", "Símil y metáfora (recursos)", "Lengua Extranjera: Past Time", "Los textos discontinuos", "El diálogo y lenguaje gestual", "El cómic: diseño y viñetas", "Lengua Originaria: Cuentos", "El punto y coma (uso)", "El adverbio y su función", "Lenguaje, lengua y habla", "Técnicas: los esquemas"]
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Guerra Federal: liberales", "Consecuencias Guerra Federal", "Mapa de pérdidas territoriales", "Usurpación del Litoral 1879", "Acción heroica: Genoveva R.", "Juanito Pinto y el tambor", "Guerra del Chaco: causas", "Defensa de la soberanía", "Héroes del Chaco regional", "Culturas precoloniales Bol.", "El Imperio Incaico (estudio)", "Pueblos originarios antiguos"],
      "SEGUNDO TRIMESTRE": ["Invasión española: impacto", "Economía en la época colonial", "Organización social colonial", "Resistencia indígena (colonia)", "Movimientos independentistas", "Creación República de Bolivia", "El tributo indígena (historia)", "Rebeliones indígenas (S. XIX)", "Líderes: Túpac Katari", "Heroínas de la Coronilla", "Héroes de la independencia", "Formación identidad Rep."],
      "TERCER TRIMESTRE": ["Mujeres lideresas de Bolivia", "Aportes femeninos históricos", "Lucha pueblos afrobolivianos", "Construcción Estado Plur.", "Asamblea Constituyente", "Fundación Estado Plurinacional", "La CPE: modelo de Estado", "Derechos fundamentales CPE", "Sociedad plural y convivencia", "Ejercicio del poder social", "Valores democráticos actual", "Identidad y pluralismo social"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["Dibujo infantil de fauna", "Dibujo infantil de flora", "Dibujo paisajes naturales", "El objeto, la luz y sombra", "Teoría de la sombra básica", "Degradación tonal volumen", "Sensación tridimensional", "Periódico mural: diseño", "Prevención violencia género", "Mensajes visuales de respeto", "Trazado artístico avanzado", "Composición y equilibrio"],
      "SEGUNDO TRIMESTRE": ["Diseños decorativos ancest.", "Manejo de escuadras (trazado)", "Pictogramas regionales", "Petroglifos: iconografía", "Ángulos con transportador", "Medición de ángulos técnica", "Caligrafía V: trazo técnico", "Precisión trazado manual", "Simetría en el arte Bol.", "Geometría en arquitectura", "Arte decorativo de pueblos", "Estética en dibujo técnico"],
      "TERCER TRIMESTRE": ["Círculo cromático (obtención)", "Teoría color (LC, LO)", "Sensaciones color pueblos", "Psicología color cultura", "Acrílico sobre lienzo (inic.)", "Técnica: follaje y celaje", "Maquetismo: Abya Yala", "Escultura arcilla o masa", "Modelado figuras culturales", "Collage y técnicas mixtas", "Arte tridimens. represent.", "Exposición de artes finales"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Técnica vocal: emisión", "Relajación y respiración pro", "Higiene vocal del cantante", "Himnos y marchas: mensajes", "Entonación progresiva (LO)", "Historia himnos regionales", "Cánones 2 y 3 voces", "Canciones tradicionales Bol.", "Melodía y ritmo (elementos)", "Armonía musical básica", "Audición dirigida medios", "Identificación instrumentos"],
      "SEGUNDO TRIMESTRE": ["Cuidado Madre Tierra (canc.)", "Coro infantil ecológico", "Escritura de signos musicales", "Uso de figuras de duración", "Rítmica escritura vocal", "Ensambles melódicos grupo", "Ensambles rítmicos grupales", "Ensambles armónicos aula", "Clasificación instrumentos", "Vientos y percusión técnica", "Lectura rítmica y solfeo", "Composición melodías simples"],
      "TERCER TRIMESTRE": ["Compases simples: 2/4", "Compases: 3/4 y 4/4", "Ritmo y danza en compases", "Lectura ritmos bolivianos", "Instrumento viento (elección)", "Interpretación instrumental", "Danzas de las regiones Bol.", "Instrumentos por geografía", "Ciclo productivo y música", "Ciclo espiritual y religioso", "Ensamble instrumental/coro", "Presentación artística final"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométr.: P/T", "Nutrición e hidratación pro", "Hábitos de higiene deportiva", "Respiración ejercicios control", "Capacidades de resistencia", "Velocidad y fuerza (juegos)", "Flexibilidad y movilidad", "Gimnasia: metodología", "Ejercicios de orden y giros", "Formaciones: filas/columnas", "Calentamiento: etapas fis.", "Coordinación dinámica grupal"],
      "SEGUNDO TRIMESTRE": ["Mini atletismo: relevos", "Resistencia aeróbica pro", "Salto triple avanzado", "Salto largo técnica", "Lanzamiento vórtex dist.", "Mini baloncesto: movimientos", "Parada de 1 y 2 tiempos", "Cambio dirección y drible", "Equidad de género deporte", "Mini voleibol: voleo alto", "Voleo bajo y antebrazo", "Saques y desplazamientos"],
      "TERCER TRIMESTRE": ["Mini fútbol: golpeo balón", "Pases y recepciones pro", "Cabeceo y conducción balón", "Remate a portería técnica", "Reglas fútbol (igualdad)", "Iniciación al Tenis de Mesa", "Respeto de género deporte", "Saque y golpe pala técnica", "Ajedrez: valor de piezas", "Movimientos especiales", "Jaque y mates básicos", "Notación ajedrecística"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["Pisos ecológicos de Bolivia", "Cuencas y clima relación", "Flora y fauna por región", "Erosión del suelo acción", "Acción natural y artificial", "Efectos en la biodiversidad", "Ciclo integral del agua", "Saneamiento y reducción ries.", "Actuación en emergencias", "Señalética de evacuación", "Sustancias puras y mezclas", "Energías: rad./mag./mec."],
      "SEGUNDO TRIMESTRE": ["Sist. respiratorio estruct.", "Efectos cigarrillo y aire", "Sist. circulatorio función", "Higiene y cuidado cardíaco", "Sist. digestivo trastornos", "Sist. reproductores función", "Gestión Menstrual Digna", "Alimentos energéticos", "Alimentos reguladores/form.", "Dieta equilibrada y salud", "Medicina natural y convenc.", "Uso responsable medicinas"],
      "TERCER TRIMESTRE": ["Fotosíntesis: proceso", "Importancia de clorofila", "El Bosque equilibrio T.", "Biodiversidad: recuperación", "Especies en extinción", "El agua en el planeta Tierra", "Distribución agua dulce/S.", "Fenómenos del agua Tierra", "Sol, Luna y Tierra (rel.)", "Influencia astral en vida", "Incidencia Luna en agro", "Sistemas vivos y energía"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Múltiplos y divisores", "Números primos y compuestos", "Criterios de divisibilidad", "Descomposición factorial", "Mínimo común múltiplo (mcm)", "Máximo común divisor (mcd)", "Fracciones equivalentes", "Fracciones homog./heterog.", "Amplificación y simplificac.", "Adición y resta fracciones", "Mult. y div. fracciones", "Problemas fraccionarios comp."],
      "SEGUNDO TRIMESTRE": ["Cuadriláteros: clasificación", "Perímetro de figuras planas", "Área de figuras planas", "Paralelogramo propiedades", "Paralelismo e intersección", "Perpendicularidad técnica", "Plano cartesiano: puntos", "Figuras en plano cartesiano", "Razones y proporciones", "Serie de razones iguales", "Magnitudes proporcionales", "Regla de tres simple"],
      "TERCER TRIMESTRE": ["Superficie: unidades m2", "Volumen: unidades m3", "Múltiplos del metro (S/V)", "Equivalencias superficie/V.", "Relación volumen/capacidad", "Medidas no convencionales", "NyPIOS: capacidad local", "Potencia: ¿qué es?", "Términos de la potencia", "Potencia base 10 y 100", "Pictogramas estadísticos", "Gráfico de barras simples"]
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Cosecha de agua: mecanis.", "Tecnologías locales agua", "Sist. riego: inundación", "Riego aspersión y goteo", "Elaboración alimentos nut.", "Deshidratación local prod.", "Seguridad alimentaria téc.", "Transformación productos", "Robótica: fundamentos", "Tipos y funciones robots", "Características robot móvil", "Robótica y productividad"] ,
      "SEGUNDO TRIMESTRE": ["Componentes electrónicos", "Motores y transformadores", "Diseño físico robot móvil", "Diseño digital del robot", "Plano construcción técnica", "Fuentes de energía (pilas)", "Baterías recargables uso", "Hoja cálculo Excel: celdas", "Funciones básicas de Excel", "Gráfico de barras en Excel", "Gestión de datos técnicos", "Seguridad circuitos básicos"],
      "TERCER TRIMESTRE": ["Google Drive y Jamboard", "Uso de Word en la nube", "Excel y PowerPoint móvil", "Colaboración digital (est.)", "Blogs educativos: creación", "Publicación de contenidos", "Scratch Jr: programación", "TinkerCad: diseño 3D", "Introducción S4A y Mblock", "Seguridad en la nube ética", "Netiqueta en blogs esc.", "Proyecto tecnológico final"]
    }
  },
  "6to Año de Escolaridad": {
    "Valores Espiritualidades y Religiones": {
      "PRIMER TRIMESTRE": ["Valores del Abya Yala", "Identidad sociocomunitaria", "Espiritualidad en las artes", "Religiosidad en los pueblos", "Ritos de nuestra comunidad", "Ofrendas a la Madre Tierra", "Significado de festividades", "Respeto a lo sagrado local", "Convivencia espiritual plural", "Ética de los pueblos NyPIOs", "Valores de reciprocidad T1", "Prácticas de fe comunitaria"],
      "SEGUNDO TRIMESTRE": ["Transparencia y honradez", "Honestidad en la escuela", "Regulación de la alegría", "Manejo del enojo y la ira", "Gestión de la tristeza social", "Cosmogonía en los NyPIOs", "Panteísmo y naturaleza", "Visión del mundo ancestral", "Normas de vida armónica", "Equilibrio emocional grupal", "Ética en el servicio social", "Valores de transparencia T2"],
      "TERCER TRIMESTRE": ["Tolerancia y respeto mutuo", "Valor de la diferencia social", "Autonomía de los pueblos", "Trilogía andina (principios)", "Ama Sua, Llulla y Quella", "Mi identidad: quién soy yo", "Soy único en la diversidad", "Autoconocimiento personal", "Liderazgo en la comunidad", "Soberanía y Vivir Bien", "Autonomía y gestión social", "Convivencia plural pacífica"]
    },
    "Comunicación y Lenguajes": {
      "PRIMER TRIMESTRE": ["La canción: comprensión", "Acentuación doble y triple", "Intencionalidad del hablante", "Lengua Extranjera: Museums", "Cuento de miedo (recursos)", "Letras c, s, z (ortografía)", "Estructura del sujeto (análisis)", "Lengua Originaria: El mito", "La mesa redonda (práctica)", "Técnicas: el cuadro SQA", "El sociodrama (expresión)", "Lectura rápida y eficaz"],
      "SEGUNDO TRIMESTRE": ["Texto expositivo-científico", "Uso de la X y dígrafo CC", "Significado de las palabras", "Lengua Extranjera: Jobs", "El afiche: diseño y función", "Uso de los dos puntos (:)", "Concordancia oración simple", "Lengua Originaria: Sucesos", "El discurso: escritura pro", "Recursos para hablar en público", "La novela corta (lectura)", "Técnicas: el parafraseo"],
      "TERCER TRIMESTRE": ["La autobiografía (estructura)", "Uso del paréntesis (reglas)", "El testimonio (escritura)", "Lengua Extranjera: My diary", "El texto dramático (tipos)", "Formas simples y compuestas", "El teatro: diálogos y voz", "Lengua Originaria: Diálogos", "Plan de redacción (escritura)", "Redes sociales: seguridad", "Síntesis argumental (TIC)", "Modos del verbo (análisis)"]
    },
    "Ciencias Sociales": {
      "PRIMER TRIMESTRE": ["Org. política en Abya Yala", "Pueblos Norte, Centro, Sur", "Convivencia de los pueblos", "Invasión europea (impacto)", "Resistencia de los pueblos", "Lucha contra la exclusión", "Rol de la Iglesia Colonial", "Poder en la época colonial", "Historia territorial de Bolivia", "Pérdidas de guerra (historia)", "Tratados diplomáticos (límites)", "Geografía política histórica"],
      "SEGUNDO TRIMESTRE": ["Los Barones del Estaño", "Saqueo de minerales (estaño)", "Revolución Nacional de 1952", "Períodos dictatoriales (S. XX)", "Seguridad vial: estadísticas", "Prevención de accidentes vía", "Libertad, diálogo e inclusión", "Igualdad en instituciones", "Participación ciudadana real", "Mecanismos contra el Bullying", "Tipos de violencia (causas)", "Consecuencias del acoso esc."],
      "TERCER TRIMESTRE": ["Modelo económico boliviano", "Redistribución de la riqueza", "Política como servicio social", "Derecho universal al agua", "El agua en la CPE (Bolivia)", "Democracia representativa", "Democracia participativa", "Democracia comunitaria", "Pilares del desarrollo patrio", "Bolivia Digna y Soberana", "Soberanía tecnológica/cient.", "Vivir Bien como horizonte"]
    },
    "Artes Plásticas y Visuales": {
      "PRIMER TRIMESTRE": ["Dibujo Técnico: polígonos", "Polígonos regulares complejo", "Diseño de polígonos estrella", "Diseño de carátulas (diagrama)", "Diseño y calado de letras", "Historia del Arte: Aymara", "Arte de la cultura Quechua", "Arte de la nación Guaraní", "Arte colonial en Bolivia", "Vestigios de arte regional", "Simbolismo prehispánico", "Calado manual en papel"],
      "SEGUNDO TRIMESTRE": ["Dibujo: composición y encaje", "Concepto de encuadre real", "Interpretación artística cuento", "Manejo instrumentos dibujo", "Sombreado: técnica achurado", "Sombreado: técnica puntillismo", "Sombreado: difuminado/liso", "Dibujo digital (Sketchbook)", "Caligrafía VI: estética pro", "Paisaje: contrastes de color", "Pintura marina y atardecer", "Pintura decorativa en vasija"],
      "TERCER TRIMESTRE": ["Obras de artistas bolivianos", "Apreciación de arte nacional", "ESCULTURA: maquetaría social", "Relieve y volumen en maqueta", "Orfebrería en arcilla técnica", "Tallado en jabón (expresión)", "Modelado avanzado (arcilla)", "Texturas en la escultura", "Composiciones materiales mix.", "Arte contemporáneo escolar", "Pensamiento crítico en arte", "Exposición de artes finales"]
    },
    "Educación Musical": {
      "PRIMER TRIMESTRE": ["Técnica vocal: articulación", "Correcta posición al cantar", "Análisis de Himnos patrios", "Entonación de marchas (sign.)", "Polifonía vocal: 3 voces", "Cánones a cuatro voces reg.", "Apreciación melódica Bol.", "Géneros musicales de tierra", "Elementos: melodía y ritmo", "Armonía de música boliviana", "Historia de himnos depart.", "Vocalización y afinación pro"],
      "SEGUNDO TRIMESTRE": ["Canciones de reflexión social", "Coro infantil: valores (LO)", "Escritura de signos (pentag.)", "Claves, notas y silencios pro", "Creaciones rítmicas (frases)", "Repertorio inst. originario", "Repertorio folclórico regional", "Lectura figuras compuestas", "Ensambles inst. complejos", "Clasificación instrumentos M.", "Composición ritmos escolares", "Teoría y solfeo avanzado"],
      "TERCER TRIMESTRE": ["Compás simple y compuesto", "Compases: 6/8 y 2/8 (ritmo)", "Danzas del Estado Plur.", "Escritura melodías autóctonas", "Interpretación regional técnica", "Historia de danzas típicas", "Danzas autóctonas resaltantes", "Ritmos del folklore nacional", "Ensamble final: orquesta/coro", "Lectura partituras populares", "Audición música universal", "Presentación de graduación"]
    },
    "Educación Física y Deportes": {
      "PRIMER TRIMESTRE": ["Medidas antropométricas pro", "Nutrición y alimentación sana", "Respiración para el deporte", "Equilibrio estático/dinámico", "Hidratación: fases del dep.", "Gimnasia rítmica y artística", "Expresión corporal escénica", "Ejercicios a manos libres", "Rodamiento adelante y atrás", "Rodamiento en posición C y V", "Rodamiento carpado técnica", "Evaluación capacidades físicas"],
      "SEGUNDO TRIMESTRE": ["Mini Atletismo: técnica pro", "Carreras, saltos y lanzam.", "Reglas específicas atletismo", "Baloncesto: sistemas de juego", "Táctica ofensiva/defensiva B.", "Organización de campeonatos", "Voleibol: sistemas avanzados", "Táctica de equipo voleibol", "Reglamento oficial deportes", "Resistencia aeróbica planif.", "Lógica de juego y arbitraje", "Práctica deportiva técnica"],
      "TERCER TRIMESTRE": ["Fútbol: sistemas de juego", "Táctica ofensiva en fútbol", "Defensa zonal y marcación", "Tenis de mesa: reglamento", "Técnicas de golpe y saque T.", "Encuentros recreativos corpo.", "Ajedrez: valor de piezas pro", "Movimientos: enroque/peón P.", "Estrategia: jaque y mates", "Notación ajedrecística pro", "Liderazgo en el campo juego", "Torneo deportivo de clausura"]
    },
    "Ciencias Naturales": {
      "PRIMER TRIMESTRE": ["La pubertad: fisiología", "Anatomía en la pubertad", "Educación integral sex. (EIS)", "Sist. glandular y hormonas", "Niveles de org. biológica", "Célula, tejido y órganos", "Microorganismos y virus", "Prevención salud integral", "Nutrición: proteínas/grasas", "Vitaminas y minerales dieta", "Las drogas: efectos nocivos", "Prevención de adicciones"],
      "SEGUNDO TRIMESTRE": ["Pisos ecológicos (cuencas)", "La cuenca como reservorio", "Biodiversidad en el Abya Y.", "Sistemas de agua (conv/alt)", "Gestión de residuos (O e I)", "Protección de la Madre T.", "Desastres: amenaza y riesgo", "Mapa de amenazas y planes", "Elementos: tabla periódica", "Energía eléctrica y química", "Energía nuclear (noción)", "Uso y cuidado de energías"],
      "TERCER TRIMESTRE": ["Reproducción de plantas", "Semillas y agricultura org.", "Cobertura vegetal y suelo", "Cadena trófica (equilibrio)", "Transferencia de vida (seres)", "Atmósfera: capas y fenómenos", "Cuidado de la capa de ozono", "Sistema Solar: constitución", "Características de planetas", "Exploración espacial (TIC)", "Tecnología en astronomía", "Evaluación final naturales"]
    },
    "Matemática": {
      "PRIMER TRIMESTRE": ["Números enteros (Z)", "El 0 y números negativos", "Recta numérica y valor abs.", "Adición y resta de Z (1-3d)", "Propiedades de los números Z", "Signos de agrupación en Z", "Operaciones combinadas Z", "Problemas de adición/resta Z", "Ángulos: medidas y const.", "Paralelismo y perpendicular", "Polígonos regulares/irreg.", "Área y volumen: prismas"],
      "SEGUNDO TRIMESTRE": ["Multiplicación de Z (1-3d)", "División de Z (1-3d)", "Propiedades mult/div en Z", "Polinomios aritméticos de Z", "Razones y proporciones (noc)", "Serie de razones iguales", "Magnitud directamente prop.", "Magnitud inversamente prop.", "Regla de tres simple/inversa", "Tanto por ciento (%)", "Interés simple: problemas", "Proporcionalidad y medida"],
      "TERCER TRIMESTRE": ["Potenciación: términos/prop.", "Potencia exp. 0 y 1", "Producto de bases iguales", "Potencia de base 10 y 100", "Radicación: términos/prop.", "Raíz de un producto/cociente", "Raíz de raíz técnica", "Estimación de radicales", "Tablas de frec. (agrupados)", "Histograma y diagrama puntos", "Gráfico barras dobles/circ.", "Estadística del contexto"]
    },
    "Técnica Tecnológica": {
      "PRIMER TRIMESTRE": ["Plantas medicinales locales", "Procesamiento de plantas M.", "Transformación de alimentos", "Tecnología de la región", "Robótica: historia y leyes", "Componentes y funciones R.", "Seguridad manejo herramientas", "Soldadura con estaño técnica", "Kit de soldadura (práctica)", "Mecanismos técnicos ancest.", "Higiene en procesamiento A.", "Prevención accidentes tecn."],
      "SEGUNDO TRIMESTRE": ["Electrónica básica robótica", "Componentes en simuladores", "Robot seguidor de luz (C)", "Uso y bondades del Arduino", "Instalación del IDE Arduino", "Componentes/funciones Arduino", "Identificación pines entrada", "Alimentación del Arduino", "Programación semáforo LED", "Lógica programación Arduino", "Simulación circuitos Eléc.", "Pruebas en robótica móvil"],
      "TERCER TRIMESTRE": ["Excel en PC y dispositivos", "Fórmulas avanzadas en Excel", "Gestión de datos técnicos", "Programación con Robomint", "Lógica de algoritmos (TIC)", "Aplicaciones: Kahoot/Khan", "Plataformas digitales educ.", "Edición de imágenes (Canva)", "Edición de videos (Kine)", "Publicación multimedia ética", "Síntesis argumental en TICs", "Proyecto tecnológico final"]
    }
  }
};
